 $(document).ready(function(){ 
    $("#pronto").click(function(){
        $(".cxIntro").fadeOut("slow");
        $(".cxIntro2").fadeOut("slow");
    });

    $("article").hide();
    $("#iniciar").hide();
    $("#pronto").click(function(){ //iniciar o jogo
        $("#pronto").hide();
        $("#iniciar").fadeIn("slow");
    });

    //esconde todas(ou parcial) das opções
    $("#iniciar").click(function(){
        $("article").fadeIn("slow");
        $(".contagem1").hide();
        $("#escol1_1").hide();
        $("#escol1_2").hide();
        $("#escol1_3").hide();
        $(".cx2").hide();
        $("#and_1").hide();
        $("#and_2").hide();
        $(".cx3").hide();
        $("#and_3").hide();
        $("#and_4").hide();
        $(".cx4").hide();
        $(".cx5").hide();
        $("#localizar2").hide();
        $(".cx6").hide();
        $(".cx7").hide();
        $(".cx8").hide();
        $("#localizar").hide();
        $(".cx7_1").hide();
        $("#verificar").hide();
        $("#matheus").hide();
        $("#rafael").hide();
        $("#laura").hide();
        $("#bruna").hide();
        $("#thiago").hide();
        $("#matheus_1").hide();
        $("#rafael_1").hide();
        $("#laura_1").hide();
        $("#bruna_1").hide();
        $("#thiago_1").hide();
        $("#mis_matheus").hide();
        $("#mis_rafael").hide();
        $("#mis_laura").hide();
        $("#mis_bruna").hide();
        $("#mis_thiago").hide();
        $(".questiona").hide();
        $("#sim").hide();
        $("#nao0").hide();
        $("#nao1").hide();
        $("#nao2").hide();
        $("#nao3").hide();
        $("#nao4").hide();
        $(".respSim").hide();
        $("#continuar_mat").hide();
        $("#continuar_raf").hide();
        $("#continuar_lau").hide();
        $("#continuar_bru").hide();
        $("#continuar_thi").hide();
        $(".baixar").hide();
        $("#voltar").hide();
        $(".introUber").hide();
        $("#verif").hide();
        $("#naoUber").hide();
        $(".introPag").hide();
        $("#simUber").hide();
        $("#naoUber2").hide();
        $(".baixar2").hide();
        $(".iniUber").hide();
        $("#localizar3").hide();
        $("#depois").hide();
        $(".local3").hide();
        $("#verificar2").hide();
        $("#guilherme").hide();
        $("#eduardo").hide();
        $("#rafaela").hide();
        $(".uberChe").hide();
        $(".uberInd").hide();
        $(".baixar3").hide();
        $("#continuar2").hide();
        $(".iniUber2").hide();
        $(".objetivo2").hide();
        $("#localizar4").hide();
        $("#juliana").hide();
        $("#marcelo").hide();
        $(".local4").hide();
        $("#verificar3").hide();
        $("#eduardo_1").hide();
        $("#guilherme_1").hide();
        $("#rafaela_1").hide();
        $("#mis_eduardo").hide();
        $("#mis_guilherme").hide();
        $("#mis_rafaela").hide();
        $(".amiInd").hide();
        $("#continuar3").hide();
        $(".objective").hide();
        $(".comeco").hide();
        $("#marcelo_1").hide();
        $("#juliana_1").hide();
        $("#mis_marcelo").hide();
        $("#mis_juliana").hide();
        $(".introOnibus").hide();
        $("#esquerda").hide();
        $("#direita").hide();
        $("#pegaCel").hide();
        $("#olhaRua").hide();
        $(".resSugestao").hide();
        $("#verificar4").hide();
        $("#naoOnibus").hide();
        $(".IntroFrags").hide();
        $(".introFrags2").hide();
        $("#download2").hide();
        $(".baixar4").hide();
        $("#verificar5").hide();
        $("#localizar5").hide();
        $(".comeco2").hide();
        $(".encontrou").hide();
        $("#marcela").hide();
        $("#giovane").hide();
        $("#lucas").hide();
        $("#camila").hide();
        $("#marcela_1").hide();
        $("#giovane_1").hide();
        $("#lucas_1").hide();
        $("#camila_1").hide();
        $("#mis_marcela").hide();
        $("#mis_giovane").hide();
        $("#mis_lucas").hide();
        $("#mis_camila").hide();
        $(".cartaz").hide();
        $("#pesquisar").hide();
        $("#naoOnibus2").hide();
        $("#baixar5").hide();
        $("#naoOnibus3").hide();
        $(".baixar6").hide();
        $(".iniOnibus").hide();
        $("#localizar6").hide();
        $("#verificar6").hide();
        $("#roberta").hide();
        $("#edegar").hide();
        $(".encontrou2").hide();
        $("#edegar_1").hide();
        $("#roberta_1").hide();
        $("#mis_roberta").hide();
        $("#mis_edegar").hide();
        $(".iniOnibus2").hide();
        $("#ajudar").hide();
        $("#naoPode").hide();
        $(".conversa2").hide();
        $("#perguntar2").hide();
        $("#naoPode2").hide();
        $(".Indica").hide();
        $("#continuar4").hide();
        $(".ganhou").hide();
        $("#IniciarProg").hide();
        $(".comeco3").hide();
        $("#verificar7").hide();
        $(".localizou2").hide();
        $("#fernanda").hide();
        $("#julia").hide();
        $("#vitor").hide();
        $("#fernanda_1").hide();
        $("#vitor_1").hide();
        $("#julia_1").hide();
        $("#mis_fernanda").hide();
        $("#mis_vitor").hide();
        $("#mis_julia").hide();
        $(".nenhuma").hide();
        $("#continuar5_1").hide();
        $("#continuar5_2").hide();
        $("#continuar5_3").hide();
        $("#continuar5_4").hide();
        $("#continuar5_5").hide();
        $(".vez").hide();
        $("#dinheiro1").hide();
        $("#dinheiro2").hide();
        $("#dinheiro3").hide();
        $("#dinheiro4").hide();
        $("#dinheiro5").hide();
        $("#frag1").hide(); 
        $("#frag2").hide(); 
        $("#frag3").hide(); 
        $("#frag4").hide(); 
        $("#frag5").hide(); 
        $(".pagDinheiro").hide(); 
        $(".baixar7").hide();
        $("#download3_1").hide();
        $("#download3_2").hide();
        $("#download3_3").hide();
        $("#download3_4").hide();
        $("#download3_5").hide();
        $("#download4_1").hide();
        $("#download4_2").hide();
        $("#download4_3").hide();
        $("#download4_4").hide();
        $("#download4_5").hide();
        $(".comeco4").hide();
        $("#continuar6_1").hide();
        $("#continuar6_2").hide();
        $("#continuar6_3").hide();
        $("#continuar6_4").hide();
        $("#continuar6_5").hide();
        $("#continuar7_1").hide();
        $("#continuar7_2").hide();
        $("#continuar7_3").hide();
        $("#continuar7_4").hide();
        $("#continuar7_5").hide();
        $(".dialogo1").hide();
        $(".dialogo2").hide();
        $(".dialogo3").hide();
        $(".dialogo4").hide();
        $(".dialogo5").hide();
        $(".contagem2").hide();
        $(".contagem3").hide();
        $(".contagem4").hide();
        $(".pagar2").hide();
        $(".pagar3").hide();
        $(".version").hide();
    });

    $("#iniciar").click(function(){
        $("#escol1").fadeIn();
        $(".cx1").fadeIn("slow");
    });

    $("#escol1").click(function(){
        $(".cx1").hide("slow");
        $("#escol1_1").show(1000);
        $("#escol1_2").show(2000);
        $("#escol1_3").show(3000);
    });

    $("#escol1_1").click(function(){
        $("#escol1").hide("slow");
        $("#escol1_2").hide("slow");
        $("#escol1_3").hide("slow");
        $(".cx2").fadeIn();
        $("#and_1").fadeIn();
        $("#and_2").fadeIn();
    });

    $("#and_1").click(function(){
        $("#and_2").hide("slow");
        $(".cx2").hide("slow");
        $("#escol1_1").hide("slow");
        $(".cx3").fadeIn();
    });

    $("#and_1").click(function(){
        $("#and_3").fadeIn("slow");
        $("#and_4").fadeIn("slow");
    });

    $("#and_3").click(function(){
        $("#and_4").hide("slow");
        $("#and_1").hide("slow");
        $(".cx3").hide("slow");
        $(".cx4").fadeIn("slow");
        $(".cx5").fadeIn("slow");
        $("#localizar2").fadeIn();
        $(".contagem1").show(3000);
    });

    $("#localizar2").click(function(){
        $("#and_3").hide("slow");
        $(".cx4").hide("slow");
        $(".cx5").hide("slow");
        $("#verificar").fadeIn();
        $(".cx7").fadeIn();
    });
    $("#and_2").click(function(){
        $("#escol1_1").hide("slow");
        $(".cx2").hide("slow");
        $("#and_1").hide("slow");
        $(".cx8").fadeIn();
        $(".amiInd").fadeIn();
        $("#and_2").hide("slow");
        $("#continuar3").fadeIn();
    });
    $("#continuar3").click(function(){
        $(".amiInd").hide("slow");
        $(".cx8").hide("slow");
        $(".baixar").fadeIn();
        $(".objective").fadeIn();
        $(".comeco").fadeIn();
        $("#localizar").fadeIn();
        $("#continuar3").hide("slow");
        $(".contagem1").show(3000);
    });
    $("#localizar").click(function(){
        $(".cx8").hide("slow");
        $("#and_2").hide("slow");
        $(".cx7_1").fadeIn();
        $(".comeco").hide("slow");
        $("#localizar").hide("slow");
        $(".objective").hide("slow");
        $("#and_4").hide("slow");
        $(".baixar").hide("slow");
        $("#verificar").fadeIn();
    });
    //Retornar para verificar os usuarios
    $("#verificar").click(function(){
        $("#verificar").toggleClass();
        $("#localizar2").hide("slow");
        $("#localizar").hide("slow");
        $(".cx6").hide("slow");
        $("#mis_matheus").hide("slow");
        $("#matheus_1").hide("slow");
        $("#rafael_1").hide("slow");
        $("#laura_1").hide("slow");
        $("#bruna_1").hide("slow");
        $("#thiago_1").hide("slow");
        $("#matheus").fadeIn();
        $("#rafael").fadeIn();
        $("#laura").fadeIn();
        $("#bruna").fadeIn();
        $("#thiago").fadeIn();
        $("#mis_rafael").hide("slow");
        $("#mis_laura").hide("slow");
        $("#mis_bruna").hide("slow");
        $("#mis_thiago").hide("slow");
        $(".questiona").hide("slow");
        $("#sim").hide("slow");
        $("#nao0").hide("slow");
        $("#nao1").hide("slow");
        $("#nao2").hide("slow");
        $("#nao3").hide("slow");
        $("#nao4").hide("slow");
        $(".respSim").hide("slow");
        $("#continuar_mat").hide("slow");
        $("#continuar_raf").hide("slow");
        $("#continuar_lau").hide("slow");
        $("#continuar_bru").hide("slow");
        $("#continuar_thi").hide("slow");
        $("#voltar").hide("slow");
        $(".version").hide();
    });
    $("#and_4").click(function(){
        $("#and_3").hide("slow");
        $("#and_1").hide("slow");
        $(".cx3").hide("slow");
        $(".cx8").fadeIn();
        $(".amiInd").fadeIn();
        $("#and_4").hide("slow");
        $("#continuar3").fadeIn();
    });
    $("#matheus").click(function(){
        $("#matheus_1").fadeIn();
        $(".cx7").hide("slow");
        $("#rafael").hide("slow");
        $("#laura").hide("slow");
        $("#bruna").hide("slow");
        $("#thiago").hide("slow");
    });
    $("#rafael").click(function(){
        $("#rafael_1").fadeIn();
        $(".cx7").hide("slow");
        $("#matheus").hide("slow");
        $("#laura").hide("slow");
        $("#bruna").hide("slow");
        $("#thiago").hide("slow");
    });
    $("#laura").click(function(){
        $("#laura_1").fadeIn();
        $(".cx7").hide("slow");
        $("#matheus").hide("slow");
        $("#rafael").hide("slow");
        $("#bruna").hide("slow");
        $("#thiago").hide("slow");
    });
    $("#bruna").click(function(){
        $("#bruna_1").fadeIn();
        $(".cx7").hide("slow");
        $("#matheus").hide("slow");
        $("#rafael").hide("slow");
        $("#laura").hide("slow");
        $("#thiago").hide("slow");
    });
    $("#thiago").click(function(){
        $("#thiago_1").fadeIn();
        $(".cx7").hide("slow");
        $("#matheus").hide("slow");
        $("#rafael").hide("slow");
        $("#laura").hide("slow");
        $("#bruna").hide("slow");
    });
    $("#matheus_1").click(function(){
        $(".questiona").fadeIn();
        $("#matheus_1").hide("slow");
        $("#sim").show();
        $("#nao0").show();
    });
    $("#nao0").click(function(){
        $(".questiona").hide("slow");
        $("#sim").hide("slow");
        $("#nao0").hide("slow");
        $("#matheus").hide("slow");
        $("#mis_matheus").fadeIn("slow");
        $(".version").show(2000);
    });
    $("#rafael_1").click(function(){
        $("#rafael_1").hide("slow");
        $(".questiona").fadeIn();
        $("#sim").show();
        $("#nao1").show();
    });
    $("#nao1").click(function(){
        $(".questiona").hide("slow");
        $("#sim").hide("slow");
        $("#nao1").hide("slow");
        $("#rafael").hide("slow");
        $("#mis_rafael").fadeIn("slow");
        $(".version").show(2000);
    });
    $("#laura_1").click(function(){
        $("#laura_1").hide("slow");
        $(".questiona").fadeIn();
        $("#sim").show();
        $("#nao2").show();
    });
    $("#nao2").click(function(){
        $(".questiona").hide("slow");
        $("#sim").hide("slow");
        $("#nao2").hide("slow");
        $("#laura").hide("slow");
        $("#mis_laura").fadeIn("slow");
        $(".version").show(2000);
    });
    $("#bruna_1").click(function(){
        $("#bruna_1").hide("slow");
        $(".questiona").fadeIn();
        $("#sim").show();
        $("#nao3").show();
    });
    $("#nao3").click(function(){
        $("#sim").hide("slow");
        $("#nao3").hide("slow");
        $(".questiona").hide("slow");
        $("#bruna").hide("slow");
        $("#mis_bruna").fadeIn("slow");
        $(".version").show(2000);
    });
    $("#thiago_1").click(function(){
        $("#thiago_1").hide("slow");
        $(".questiona").fadeIn();
        $("#sim").show();
        $("#nao4").show();
    });
    $("#nao4").click(function(){
        $(".questiona").hide("slow");
        $("#sim").hide("slow");
        $("#nao4").hide("slow");
        $("#thiago").hide("slow");
        $("#mis_thiago").fadeIn("slow");
        $(".version").show(2000);
    });
    $("#sim").click(function(){
        $(".respSim").fadeIn();
        $("#nao0").hide("slow");
        $("#nao1").hide("slow");
        $("#nao2").hide("slow");
        $("#nao3").hide("slow");
        $("#nao4").hide("slow");
        $("#sim").hide("slow");
        $(".questiona").hide("slow");
        $("#voltar").fadeIn();
        $("#matheus").hide("slow");
        $("#rafael").hide("slow");
        $("#laura").hide("slow");
        $("#bruna").hide("slow");
        $("#thiago").hide("slow");
    });
    $("#voltar").click(function(){
        $("#verificar").show("slow");
        $("#matheus").hide("slow");
        $("#rafael").hide("slow");
        $("#laura").hide("slow");
        $("#bruna").hide("slow");
        $("#thiago").hide("slow");
        $("#voltar").hide("slow");
        $(".respSim").hide("slow");
    });

    $("#escol1_2").click(function(){
        $("#escol1_1").hide("slow");
        $("#escol1_3").hide("slow");
        $("#escol1").hide("slow");
        $(".introUber").fadeIn();
        $("#verif").fadeIn();
        $("#naoUber").fadeIn();
    });
    $("#verif").click(function(){
        $(".introPag").fadeIn();
        $("#naoUber").hide("slow");
        $(".introUber").hide("slow");
        $("#escol1_2").hide("slow");
        $("#simUber").fadeIn();
        $("#naoUber2").fadeIn();
    });
    $("#simUber").click(function(){
        $("#verif").hide("slow");
        $("#naoUber2").hide("slow");
        $(".introPag").hide("slow");
        $(".baixar2").fadeIn();
        $(".iniUber").fadeIn();
        $("#localizar3").fadeIn();
        $("#depois").fadeIn();
        $(".contagem1").show(3000);
    });
    $("#localizar3").click(function(){
        $(".local3").fadeIn();
        $("#verificar2").fadeIn();
        $("#simUber").hide("slow");
        $(".iniUber").hide("slow");
        $(".baixar2").hide("slow");
        $(".cx5").show(2000);
        $("#depois").hide("slow");
        $("#localizar3").hide("fast");
    });
    //Verificar da parte que há 3 pessoas encontradas:
    $("#verificar2").click(function(){
        $("#eduardo").fadeIn();
        $("#guilherme").fadeIn();
        $("#rafaela").fadeIn();
        $(".cx5").hide("slow");
        $(".local3").hide("slow");
        $("#eduardo_1").hide();
        $("#guilherme_1").hide();
        $("#rafaela_1").hide();
        $("#mis_eduardo").hide();
        $("#mis_guilherme").hide();
        $("#mis_rafaela").hide();
        $(".version").hide();
    });

    $("#naoUber").click(function(){
        $(".uberChe").fadeIn();
        $("#escol1_2").hide("slow");
        $(".introUber").hide("slow");
        $("#verif").hide("slow");
        $(".uberInd").fadeIn();
        $("#continuar2").fadeIn();
    });
    $("#continuar2").click(function(){
        $(".uberChe").hide("slow");
        $(".uberInd").hide("slow");
        $("#naoUber").hide("slow");
        $("#naoUber2").hide("slow");
        $("#depois").hide("slow");
        $("#simUber").hide("slow");
        $(".baixar3").fadeIn();
        $(".iniUber2").fadeIn();
        $(".objetivo2").fadeIn();
        $("#localizar4").fadeIn();
        $(".contagem1").show(3000);
    });
    $("#localizar4").click(function(){
        $(".baixar3").hide();
        $(".iniUber2").hide();
        $(".objetivo2").hide();
        $(".baixar3").hide();
        $(".local4").fadeIn();
        $("#continuar2").hide("slow");
        $("#verificar3").fadeIn();
    });
    //Verificar das duas opções
    $("#verificar3").click(function(){
        $(".local4").hide("slow");
        $("#localizar4").hide("slow");
        $("#marcelo").fadeIn();
        $("#juliana").fadeIn();
        $("#marcelo_1").hide("slow");
        $("#juliana_1").hide("slow");
        $("#mis_marcelo").hide("slow");
        $("#mis_juliana").hide("slow");
        $(".version").hide();
    });
    $("#naoUber2").click(function(){
        $(".uberChe").fadeIn();
        $("#simUber").hide("slow");
        $("#verif").hide("slow");
        $(".introPag").hide("slow");
        $(".uberInd").fadeIn();
        $("#continuar2").show("slow");
    });
    $("#depois").click(function(){
        $("#localizar3").hide("slow");
        $(".iniUber").hide("slow");
        $(".baixar2").hide("slow");
        $(".uberChe").fadeIn();
        $("#continuar2").fadeIn();
    });
    $("#eduardo").click(function(){
        $("#guilherme").hide("slow");
        $("#rafaela").hide("slow");
        $("#eduardo_1").fadeIn();
    });
    $("#guilherme").click(function(){
        $("#rafaela").hide("slow");
        $("#eduardo").hide("slow");
        $("#guilherme_1").fadeIn();
    });
    $("#rafaela").click(function(){
        $("#eduardo").hide("slow");
        $("#guilherme").hide("slow");
        $("#rafaela_1").fadeIn();
    });
    $("#eduardo_1").click(function(){
        $("#mis_eduardo").fadeIn();
        $("#eduardo").hide("slow");
        $(".version").show(2000);
    });
    $("#guilherme_1").click(function(){
        $("#mis_guilherme").fadeIn();
        $("#guilherme").hide("slow");
        $(".version").show(2000);
    });
    $("#rafaela_1").click(function(){
        $("#mis_rafaela").fadeIn();
        $("#rafaela").hide("slow");
        $(".version").show(2000);
    });
    $("#marcelo").click(function(){
        $("#juliana").hide("slow");
        $("#marcelo_1").fadeIn();
    });
    $("#juliana").click(function(){
        $("#juliana_1").fadeIn();
        $("#marcelo").hide("slow");
    });
    $("#juliana_1").click(function(){
        $("#mis_juliana").fadeIn();
        $("#juliana").hide();
        $(".version").show(2000);
    });
    $("#marcelo_1").click(function(){
        $("#mis_marcelo").fadeIn();
        $("#marcelo").hide("slow");
        $(".version").show(2000);
    });
    $("#escol1_3").click(function(){
        $(".introOnibus").fadeIn();
        $("#esquerda").show();
        $("#direita").show();
        $("#escol1_1").hide("slow");
        $("#escol1_2").hide("slow");
        $("#escol1").hide("slow");
    });
    $("#esquerda").click(function(){
        $("#direita").hide("slow");
        $("#escol1_3").hide("slow");
        $(".introOnibus").hide("slow");
        $("#pegaCel").fadeIn();
        $("#olhaRua").fadeIn();
    });
    $("#pegaCel").click(function(){
        $("#olhaRua").hide("slow");
        $(".resSugestao").fadeIn();
        $("#verificar4").show();
        $("#naoOnibus").show();
        $("#esquerda").hide();
    });
    $("#verificar4").click(function(){
        $("#pegaCel").hide("slow");
        $(".resSugestao").hide("slow");
        $("#naoOnibus").hide("slow");
        $(".IntroFrags").show();
        $("#download2").show();
    });
    $("#download2").click(function(){
        $(".IntroFrags").hide("slow");
        $("#verificar4").hide("slow");
        $(".baixar4").show();
        $("#localizar5").show();
        $(".comeco2").show();
        $(".contagem1").show(3000);
    });
    $("#localizar5").click(function(){
        $('.comeco2').hide("slow");
        $('.baixar4').hide("slow");
        $('#download2').hide("slow");
        $(".encontrou").show();
        $("#verificar5").show();
    });
    $("#verificar5").click(function(){
        $(".encontrou").hide("slow");
        $("#localizar5").hide("slow");
        $("#marcela").show();
        $("#giovane").fadeIn("slow");
        $("#lucas").fadeIn("slow");
        $("#camila").fadeIn("slow");
    });
    $("#marcela").click(function(){
        $("#giovane").hide("slow");
        $("#lucas").hide("slow");
        $("#camila").hide("slow");
        $("#marcela_1").fadeIn();
    });
    $("#marcela_1").click(function(){
        $("#marcela").hide("slow");
        $("#mis_marcela").fadeIn();
        $(".version").show(2000);
    });
    $("#giovane").click(function(){
        $("#giovane_1").fadeIn();
        $("#marcela").hide("slow");
        $("#lucas").hide("slow");
        $("#camila").hide("slow");
    });
    $("#giovane_1").click(function(){
        $("#giovane").hide("slow");
        $("#mis_giovane").fadeIn();
        $(".version").show(2000);
    });
    $("#lucas").click(function(){
        $("#lucas_1").fadeIn();
        $("#marcela").hide("slow");
        $("#camila").hide("slow");
        $("#giovane").hide("slow");
    });
    $("#lucas_1").click(function(){
        $("#lucas").hide("slow");
        $("#mis_lucas").fadeIn();
        $(".version").show(2000);
    });
    $("#camila").click(function(){
        $("#camila_1").fadeIn();
        $("#marcela").hide("slow");
        $("#giovane").hide("slow");
        $("#lucas").hide("slow");
    });
    $("#camila_1").click(function(){
        $("#camila").hide("slow");
        $("#mis_camila").fadeIn();
        $(".version").show(2000);
    });
    //esconde os 5
    $("#verificar5").click(function(){
        $("#marcela_1").hide("slow");
        $("#giovane_1").hide("slow");
        $("#lucas_1").hide("slow");
        $("#camila_1").hide("slow");
        $("#mis_camila").hide("slow");
        $("#mis_giovane").hide("slow");
        $("#mis_lucas").hide("slow");
        $("#mis_marcela").hide("slow");
        $(".version").hide();
    });
    $("#olhaRua").click(function(){
        $("#escol1_3").hide("slow");
        $(".introOnibus").hide("slow");
        $("#esquerda").hide("slow");
        $(".cartaz").fadeIn();
        $("#pegaCel").hide("slow");
        $("#pesquisar").show();
        $("#naoOnibus2").show();
    });
    $("#pesquisar").click(function(){
        $(".cartaz").hide("slow");
        $("#naoOnibus2").hide("slow");
        $("#direita").hide("slow");
        $(".introFrags2").fadeIn();
        $("#baixar5").fadeIn();
        $("#olhaRua").hide("slow");
        $("#naoOnibus3").fadeIn();
    });
    $("#baixar5").click(function(){
        $(".introFrags2").hide("slow");
        $("#pesquisar").hide("slow");
        $("#naoOnibus3").hide("slow");
        $(".baixar6").fadeIn();
        $(".iniOnibus").fadeIn();
        $("#localizar6").fadeIn();
        $(".contagem1").show(3000);
        $("#baixar5").hide("slow");
    });
    $("#localizar6").click(function(){
        $(".baixar6").hide("slow");
        $(".iniOnibus").hide("slow");
        $(".encontrou2").fadeIn();
        $("#verificar6").fadeIn();
    });
    //recolhe todos de edegar e roberta
    $("#verificar6").click(function(){
        $("#roberta").fadeIn();
        $("#edegar").fadeIn();
        $("#localizar6").hide("slow");
        $(".encontrou2").hide("slow");
        $("#roberta_1").hide("slow");
        $("#edegar_1").hide("slow");
        $("#mis_edegar").hide("slow");
        $("#mis_roberta").hide("slow");
        $(".version").hide();
    });
    $("#roberta").click(function(){
        $("#edegar").hide("slow");
        $("#roberta_1").fadeIn();
    });
    $("#edegar").click(function(){
        $("#roberta").hide("slow");
        $("#edegar_1").fadeIn();
    });
    $("#edegar_1").click(function(){
        $("#edegar").hide("slow");
        $("#mis_edegar").fadeIn();
        $(".version").show(2000);
    });
    $("#roberta_1").click(function(){
        $("#roberta").hide("slow");
        $("#mis_roberta").fadeIn();
        $(".version").show(2000);
    });
    $("#direita").click(function(){
        $("#escol1_3").hide("slow");
        $(".introOnibus").hide("slow");
        $("#esquerda").hide("slow");
        $(".iniOnibus2").fadeIn();
        $("#naoPode").fadeIn();
        $("#ajudar").fadeIn();
    });
    $("#ajudar").click(function(){
        $("#naoPode").hide("slow");
        $("#direita").hide("slow");
        $(".iniOnibus2").hide("slow");
        $(".conversa2").fadeIn();
        $("#perguntar2").fadeIn();
        $("#naoPode2").fadeIn();
    });
    $("#perguntar2").click(function(){
        $(".conversa2").hide("slow");
        $("#naoPode2").hide("slow");
        $("#ajudar").hide("slow");
        $(".introFrags2").fadeIn();
        $("#perguntar2").hide("slow");
        $(".Indica").fadeIn("slow");
        $("#continuar4").fadeIn();
    });
    $("#continuar4").click(function(){
        $(".introFrags2").hide("slow");
        $(".Indica").hide("slow");
        $(".ganhou").fadeIn();
        $("#IniciarProg").fadeIn();
        $(".contagem2").show(3000);
    });
    $("#IniciarProg").click(function(){
        $(".Indica").hide("slow");
        $(".ganhou").hide("slow");
        $(".comeco3").fadeIn();
        $("#continuar4").hide("slow");
        $(".localizou2").show();
        $("#verificar7").fadeIn();
    });
    $("#verificar7").click(function(){
       $(".localizou2").hide("slow");
       $(".comeco3").hide("slow");
       $("#IniciarProg").hide("slow");
       $("#fernanda").fadeIn();
       $("#julia").fadeIn();
       $("#vitor").fadeIn();
       $("#fernanda_1").hide("slow");
       $("#vitor_1").hide("slow");
       $("#julia_1").hide("slow");
       $("#mis_fernanda").hide("slow");
       $("#mis_vitor").hide("slow");
       $("#mis_julia").hide("slow");
    });
    $("#fernanda").click(function(){
        $("#fernanda_1").fadeIn();
        $("#vitor").hide("slow");
        $("#julia").hide("slow");
    });
    $("#fernanda_1").click(function(){
        $("#fernanda").hide("slow");
        $("#mis_fernanda").fadeIn();
    });
    $("#vitor").click(function(){
        $("#vitor_1").fadeIn();
        $("#fernanda").hide("slow");
        $("#julia").hide("slow");
    });
    $("#vitor_1").click(function(){
        $("#vitor").hide("slow");
        $("#mis_vitor").fadeIn();
    });
    $("#julia").click(function(){
        $("#julia_1").fadeIn();
        $("#vitor").hide("slow");
        $("#fernanda").hide("slow");
    });
    $("#julia_1").click(function(){
        $("#julia").hide("slow");
        $("#mis_julia").fadeIn();
    });

    //CATEGORIA DE "NÃO"
    $("#naoOnibus").click(function(){
        $(".nenhuma").show();
        $("#pegaCel").hide("slow");
        $(".resSugestao").hide("slow");
        $("#verificar4").hide("slow");
        $("#continuar5_1").fadeIn();
    });
    $("#naoOnibus2").click(function(){
        $(".nenhuma").show();
        $("#pesquisar").hide("slow");
        $("#olhaRua").hide("slow");
        $(".cartaz").hide("slow");
        $("#continuar5_2").fadeIn();
    });
    $("#naoOnibus3").click(function(){
        $(".nenhuma").show();
        $("#pesquisar").hide("slow");
        $(".introFrags2").hide("slow");
        $("#baixar5").hide("slow");
        $("#continuar5_3").fadeIn();
    });
    $("#naoPode").click(function(){
        $(".nenhuma").show();
        $("#direita").hide("slow");
        $(".iniOnibus2").hide("slow");
        $("#ajudar").hide("slow");
        $("#continuar5_4").fadeIn();
    });
    $("#naoPode2").click(function(){
        $(".nenhuma").show();
        $("#ajudar").hide("slow");
        $(".conversa2").hide("slow");
        $("#perguntar2").hide("slow");
        $("#continuar5_5").fadeIn();
    });
    //continuar..
    //Formas de pagamento
    $("#continuar5_1").click(function(){
        $(".nenhuma").hide("slow");
        $("#naoOnibus").hide("slow");
        $(".vez").fadeIn();
        $("#dinheiro1").fadeIn();
        $("#frag1").fadeIn();
    });
    $("#continuar5_2").click(function(){
        $(".nenhuma").hide("slow");
        $("#naoOnibus2").hide("slow");
        $(".vez").fadeIn();
        $("#dinheiro2").fadeIn();
        $("#frag2").fadeIn();
    });
    $("#continuar5_3").click(function(){
        $(".nenhuma").hide("slow");
        $("#naoOnibus3").hide("slow");
        $(".vez").fadeIn();
        $("#dinheiro3").fadeIn();
        $("#frag3").fadeIn();
    });
    $("#continuar5_4").click(function(){
        $(".nenhuma").hide("slow");
        $("#naoPode").hide("slow");
        $(".vez").fadeIn();
        $("#dinheiro4").fadeIn();
        $("#frag4").fadeIn();
    });
    $("#continuar5_5").click(function(){
        $(".nenhuma").hide("slow");
        $("#naoPode2").hide("slow");
        $(".vez").fadeIn();
        $("#dinheiro5").fadeIn();
        $("#frag5").fadeIn();
    });
    //Pagamento com dinheiro:
    $("#dinheiro1").click(function(){
        $("#continuar5_1").hide("slow");
        $(".vez").hide("slow");
        $("#frag1").hide("slow");
        $(".pagDinheiro").fadeIn();
        $("#download3_1").fadeIn();
    });
    $("#dinheiro2").click(function(){
        $("#continuar5_2").hide("slow");
        $("#download3_2").fadeIn();
        $("#frag2").hide("slow");
        $(".vez").hide("slow");
        $(".pagDinheiro").fadeIn();
    });
    $("#dinheiro3").click(function(){
        $("#continuar5_3").hide("slow");
        $("#download3_3").fadeIn();
        $("#frag3").hide("slow");
        $(".vez").hide("slow");
        $(".pagDinheiro").fadeIn();
    });
    $("#dinheiro4").click(function(){
        $("#continuar5_4").hide("slow");
        $("#download3_4").fadeIn();
        $("#frag4").hide("slow");
        $(".vez").hide("slow");
        $(".pagDinheiro").fadeIn();
    });
    $("#dinheiro5").click(function(){
        $("#continuar5_5").hide("slow");
        $("#download3_5").fadeIn();
        $("#frag5").hide("slow");
        $(".vez").hide("slow");
        $(".pagDinheiro").fadeIn();
    });
    //Pagemento com frags
    $("#frag1").click(function(){
        $(".vez").hide("slow");
        $("#continuar5_1").hide("slow");
        $("#dinheiro1").hide("slow");
        $("#download4_1").fadeIn();
    });
    $("#frag2").click(function(){
        $(".vez").hide("slow");
        $("#continuar5_2").hide("slow");
        $("#dinheiro2").hide("slow");
        $("#download4_2").fadeIn();
    });
    $("#frag3").click(function(){
        $(".vez").hide("slow");
        $("#continuar5_3").hide("slow");
        $("#dinheiro3").hide("slow");
        $("#download4_3").fadeIn();
    });
    $("#frag4").click(function(){
        $(".vez").hide("slow");
        $("#continuar5_4").hide("slow");
        $("#dinheiro4").hide("slow");
        $("#download4_4").fadeIn();
    });
    $("#frag5").click(function(){
        $(".vez").hide("slow");
        $("#continuar5_5").hide("slow");
        $("#dinheiro5").hide("slow");
        $("#download4_5").fadeIn();
    });
    //Download para função dinheiro
    $("#download3_1").click(function(){
        $("#frag1").hide("slow");
        $("#dinheiro1").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar6_1").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar3").fadeIn();
    });
    $("#download3_2").click(function(){
        $("#frag2").hide("slow");
        $("#dinheiro2").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar6_2").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar3").fadeIn();
    });
    $("#download3_3").click(function(){
        $("#frag3").hide("slow");
        $("#dinheiro3").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar6_3").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar3").fadeIn();
    });
    $("#download3_4").click(function(){
        $("#frag4").hide("slow");
        $("#dinheiro4").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar6_4").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar3").fadeIn();
    });
    $("#download3_5").click(function(){
        $("#frag5").hide("slow");
        $("#dinheiro5").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar6_5").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar3").fadeIn();
    });
    //Download para função frag
    $("#download4_1").click(function(){
        $("#frag1").hide("slow");
        $("#dinheiro1").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar7_1").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar2").fadeIn();
    });
    $("#download4_2").click(function(){
        $("#frag2").hide("slow");
        $("#dinheiro2").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar7_2").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar2").fadeIn();
    });
    $("#download4_3").click(function(){
        $("#frag3").hide("slow");
        $("#dinheiro3").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar7_3").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar2").fadeIn();
    });
    $("#download4_4").click(function(){
        $("#frag4").hide("slow");
        $("#dinheiro4").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar7_4").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar2").fadeIn();
    });
    $("#download4_5").click(function(){
        $("#frag5").hide("slow");
        $("#dinheiro5").hide("slow");
        $(".baixar7").fadeIn();
        $(".pagDinheiro").hide("slow");
        $(".comeco4").fadeIn();
        $("#continuar7_5").fadeIn();
        $(".contagem1").show(3000);
        $(".pagar2").fadeIn();
    });
    //Botão de continuar para dinheiro
    $("#continuar6_1").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download3_1").hide("slow");
        $(".dialogo1").fadeIn();
        $(".version").show(2000);
        $(".pagar3").hide("slow");
        $(".contagem1").hide();
        $(".contagem4").show(3000);
    });
    $("#continuar6_2").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download3_2").hide("slow");
        $(".dialogo2").fadeIn();
        $(".version").show(2000);
        $(".pagar3").hide("slow");
        $(".contagem1").hide();
        $(".contagem4").show(3000);
    });
    $("#continuar6_3").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download3_3").hide("slow");
        $(".dialogo3").fadeIn();
        $(".version").show(2000);
        $(".pagar3").hide("slow");
        $(".contagem1").hide();
        $(".contagem4").show(3000);
    });
    $("#continuar6_4").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download3_4").hide("slow");
        $(".dialogo4").fadeIn();
        $(".version").show(2000);
        $(".pagar3").hide("slow");
        $(".contagem1").hide();
        $(".contagem4").show(3000);
    });
    $("#continuar6_5").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download3_5").hide("slow");
        $(".dialogo5").fadeIn();
        $(".version").show(2000);
        $(".pagar3").hide("slow");
        $(".contagem1").hide();
        $(".contagem4").show(3000);
    });
    //Botão para continuar com frags
    $("#continuar7_1").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download4_1").hide("slow");
        $(".dialogo1").fadeIn();
        $(".version").show(2000);
        $(".pagar2").hide("slow");
        $(".contagem1").hide();
        $(".contagem3").show(3000);
    });
    $("#continuar7_2").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download4_2").hide("slow");
        $(".dialogo2").fadeIn();
        $(".version").show(2000);
        $(".pagar2").hide("slow");
        $(".contagem1").hide();
        $(".contagem3").show(3000);
    });
    $("#continuar7_3").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download4_3").hide("slow");
        $(".dialogo3").fadeIn();
        $(".version").show(2000);
        $(".pagar2").hide("slow");
        $(".contagem1").hide();
        $(".contagem3").show(3000);
    });
    $("#continuar7_4").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download4_4").hide("slow");
        $(".dialogo4").fadeIn();
        $(".version").show(2000);
        $(".pagar2").hide("slow");
        $(".contagem1").hide();
        $(".contagem3").show(3000);
    });
    $("#continuar7_5").click(function(){
        $(".baixar7").hide("slow");
        $(".comeco4").hide("slow");
        $("#download4_5").hide("slow");
        $(".dialogo5").fadeIn();
        $(".version").show(2000);
        $(".pagar2").hide("slow");
        $(".contagem1").hide();
        $(".contagem3").show(3000);
    });
});
